FROM node:16-alpine

WORKDIR /app

COPY package.json .

RUN npm install --force

RUN npm install -D @vkontakte/vk-tunnel

COPY . .

EXPOSE 10888
# required for docker desktop port mapping

CMD ["npm", "run", "tunnel"]
